### ISSUE TITLE
NuGet version of assembly not signed

### ISSUE THREAD

**Issue by KalduzovMM** [Thanood/Topshelf.Common.Logging#2]
Please sign the NuGet version assembly. We very much need it.

**Comment by vasilevig** [comment]
+1

**Comment by cd21h** [comment]
+1

**Comment by w0xpo** [comment]
+1

**Comment by korolyov2** [comment]
yes, we definitely need it too

**Comment by ivanovdmi** [comment]
It will be convenient.
+1

**Comment by Thanood** [comment]
Will do it when I return from vacation. :-)

**Comment by Thanood** [comment]
Not sure if I get this right. The assembly itself should be signed, right?
Or the NuGet package?

**Comment by Thanood** [comment]
Assembly signed, NuGet package is updated.

**Comment by KalduzovMM** [comment]
Thanks!
